package pertemuan3;

// import paket yang diperlukan
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;



public class TampilanCitra3 extends javax.swing.JFrame {

    /** Creates new form TampilanCitra */
    public TampilanCitra3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextTinggi = new javax.swing.JTextField();
        jTextLebar = new javax.swing.JTextField();
        jTextX = new javax.swing.JTextField();
        jTextY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextMerah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextHijau = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tombolGrayScale = new javax.swing.JToggleButton();
        jTextBiru = new javax.swing.JTextField();
        tombolRGB = new javax.swing.JToggleButton();
        jLabelPeringatan = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Menampilkan Citra");

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setViewportView(jLabel2);

        jButton1.setText("Ambil Gambar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Lebar");

        jLabel4.setText("Tinggi");

        jLabel5.setText("X");

        jLabel6.setText("Y");

        jLabel10.setText("jLabel10");
        jScrollPane2.setViewportView(jLabel10);

        jLabel7.setText("R");

        jLabel8.setText("G");

        jLabel9.setText("B");

        tombolGrayScale.setText("Grayscale");
        tombolGrayScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolGrayScaleActionPerformed(evt);
            }
        });

        tombolRGB.setText("RGB");
        tombolRGB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolRGBMouseClicked(evt);
            }
        });
        tombolRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolRGBActionPerformed(evt);
            }
        });

        jLabelPeringatan.setFont(new java.awt.Font("Droid Sans", 2, 13)); // NOI18N
        jLabelPeringatan.setForeground(new java.awt.Color(227, 182, 3));

        jButton2.setText("Histogram");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextLebar))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextY, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                            .addComponent(jTextX))))
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextMerah)
                                    .addComponent(jTextHijau)
                                    .addComponent(jTextBiru, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tombolRGB)
                                    .addComponent(jLabelPeringatan))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(tombolGrayScale))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextMerah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tombolGrayScale)
                            .addComponent(tombolRGB))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextHijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPeringatan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextBiru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButton2)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // membuat variabel global
    String sumber = null;
    Image ikonGambar;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser berkas = new JFileChooser();
        int ambil = berkas.showOpenDialog(jScrollPane1);

        if(ambil == JFileChooser.APPROVE_OPTION){
            sumber = berkas.getSelectedFile().getPath();
            jLabel2.setIcon(new ImageIcon(sumber));

        }

        ikonGambar = new ImageIcon(sumber).getImage();
        int lebar = ikonGambar.getWidth(null);
        int tinggi = ikonGambar.getHeight(null);

        jTextLebar.setText(Integer.toString(lebar));
        jTextTinggi.setText(Integer.toString(tinggi));

    }//GEN-LAST:event_jButton1ActionPerformed

    private static BufferedImage muatCitra(String referensi) {
        BufferedImage citra = null;
        try{
            citra = ImageIO.read(new File(referensi));
        } catch (IOException e){
            System.out.println(e.getMessage());
        }

        return citra;
    }

    private void tombolRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRGBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tombolRGBActionPerformed

    private void tombolGrayScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolGrayScaleActionPerformed
        // TODO add your handling code here:
        BufferedImage prosesGambar;
        ikonGambar = new ImageIcon(sumber).getImage();
        int ukuranX = ikonGambar.getWidth(null);
        int ukuranY = ikonGambar.getWidth(null);
        BufferedImage loading = muatCitra(sumber);
        prosesGambar = new BufferedImage(ukuranX, ukuranY, BufferedImage.TYPE_INT_RGB);
        Graphics grafik = prosesGambar.getGraphics();
        grafik.drawImage(ikonGambar, 0, 0, null);

        for (int x = 0; x < ukuranX; x++){
            for(int y =0; y < ukuranY; y++){
                int rgb = loading.getRGB(x, y);
                int alpha = (rgb << 24)&0xff;
                int merahg = (rgb >> 16)&0xff;
                int hijaug = (rgb >> 8)&0xff;
                int birug = (rgb >> 0)&0xff;
                int rataRata = (merahg + hijaug + birug) / 3;
                int grayScale = alpha | rataRata << 16 | rataRata << 8 | rataRata;
                prosesGambar.setRGB(x, y, grayScale);
            }
        }
    }//GEN-LAST:event_tombolGrayScaleActionPerformed

    private void tombolRGBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolRGBMouseClicked
        // TODO add your handling code here:

        BufferedImage loading = muatCitra(sumber);
        jTextMerah.setText("");
        jTextHijau.setText("");
        jTextBiru.setText("");

        int x = Integer.valueOf(jTextX.getText());
        int y = Integer.valueOf(jTextY.getText());

        if(x > Integer.valueOf(jTextLebar.getText()) || y > Integer.valueOf(jTextTinggi.getText())){
            jLabelPeringatan.setText("Nilai X dan Y melampaui batas!");
        } else {
            int rgb = loading.getRGB(x, y);

            int merah = (rgb >> 16) &0xff;
            int hijau = (rgb >> 8) &0xff;
            int biru = (rgb >> 0) &0xff;

            jTextMerah.setText(Integer.toString(merah));
            jTextHijau.setText(Integer.toString(hijau));
            jTextBiru.setText(Integer.toString(biru));
        }
    }//GEN-LAST:event_tombolRGBMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int ukuranX = ikonGambar.getWidth(null);
        int ukuranY = ikonGambar.getWidth(null);
        
        BufferedImage prosesGambar;
        BufferedImage loading = muatCitra(sumber);
        prosesGambar = new BufferedImage(ukuranX, ukuranY, BufferedImage.TYPE_INT_RGB);
                
        Graphics grafik = prosesGambar.getGraphics();
        grafik.drawImage(ikonGambar, 0, 0, null);
	
	// writableRaster rater = prosesGamabar.getRaster();
	for(int x = 0; x < ukuranX; x++){
            for(int y = 0; y < ukuranY; y++){
		int rgb = prosesGambar.getRGB(x, y);
		int alpha = (rgb << 24)&0xff;
		int merahg = (rgb >> 16)&0xff;
		int hijaug = (rgb >> 8)&0xff;
		int birug = (rgb >> 0)&0xff;
		int rataRata = (merahg+hijaug+birug) / 3;
		int grasScale = alpha |rataRata << 16 | rataRata << 8 | rataRata;
		
		prosesGambar.setRGB(x, y, grasScale);
            }
	}
	
	jLabel10.setIcon(new ImageIcon(prosesGambar));
	drawHistogram(prosesGambar, "Grafik");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void drawHistogram(BufferedImage gambar, String hsl){

	int lebar = gambar.getWidth();
	int tinggi = gambar.getHeight();
	int count[][] = new int[4][0x100];
	int merah = 0;
	int biru = 1;
	int hijau = 2;
	int total = lebar * tinggi;
	
	for(int x = 0; x < lebar; x++){
            for(int y = 0; y < tinggi; y++){
		
		int rgb = gambar.getRGB(x,y);
		int merahg = (rgb & 0x00ff0000) >> 16;
		int hijaug = (rgb & 0x00ff0000) >> 8;
		int birug = (rgb & 0x00ff0000);
		int grey = (merahg+hijaug+birug) / 3;
		count[merah][merahg]++;
		count[biru][birug]++;
		count[hijau][hijaug]++;
		count[3][grey]++;
		
            }
	}
	
	DefaultCategoryDataset dataset = new DefaultCategoryDataset();
	for (int f = 0; f < 0x100; f++){
            dataset.addValue(count[0][f], "Red", new Integer(f));
            dataset.addValue(count[2][f], "Blue", new Integer(f));
            dataset.addValue(count[1][f], "Green", new Integer(f));
            dataset.addValue(count[3][f], "Black", new Integer(f));
	}
	
	JFreeChart histo = ChartFactory.createBarChart("Histogram Citra", "Nilai", "Frekuensi",
		dataset, PlotOrientation.VERTICAL, false, true, false);
		
	ChartFrame frame = new ChartFrame("Histogram Citra", histo);
	histo.setBackgroundPaint(Color.white);
	final CategoryPlot plot =  (CategoryPlot) histo.getPlot();
	plot.setBackgroundPaint(Color.WHITE);
	plot.setRangeMinorGridlinePaint(Color.white);
	frame.setSize(500,350);
	frame.setLocation(380,200);
	frame.setTitle(hsl);
        frame.setVisible(true);
    }
    
    
    /**
    * @param args the comfcmand line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new TampilanCitra3().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPeringatan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextBiru;
    private javax.swing.JTextField jTextHijau;
    private javax.swing.JTextField jTextLebar;
    private javax.swing.JTextField jTextMerah;
    private javax.swing.JTextField jTextTinggi;
    private javax.swing.JTextField jTextX;
    private javax.swing.JTextField jTextY;
    private javax.swing.JToggleButton tombolGrayScale;
    private javax.swing.JToggleButton tombolRGB;
    // End of variables declaration//GEN-END:variables


}
