/*
 * Nama : Ahmad Muhar Dian Lasmita
 * NIM  : 1210520098
 * Kelas: B
 */
package pertemuan4;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author iyan
 */
public class TampilanUtama extends javax.swing.JFrame {

    /**
     * Creates new form TampilanUtama
     */
    public TampilanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelGambar = new javax.swing.JLabel();
        jButtonAmbilGambar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldX = new javax.swing.JTextField();
        jTextFieldY = new javax.swing.JTextField();
        jButtonRGB = new javax.swing.JButton();
        jPanelRGB = new javax.swing.JPanel();
        jLabelRed = new javax.swing.JLabel();
        jLabelGreen = new javax.swing.JLabel();
        jLabelBlue = new javax.swing.JLabel();
        jPanelUkuran = new javax.swing.JPanel();
        jLabelLebar = new javax.swing.JLabel();
        jLabelTinggi = new javax.swing.JLabel();
        jButtonGrayscale = new javax.swing.JButton();
        jLabelPesanError = new javax.swing.JLabel();
        jButtonHistogram = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tugas Praktikum Pengolahan Citra");

        jScrollPane1.setViewportView(jLabelGambar);

        jButtonAmbilGambar.setText("Ambil Gambar");
        jButtonAmbilGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAmbilGambarMouseClicked(evt);
            }
        });

        jLabel2.setText("X");

        jLabel3.setText("Y");

        jTextFieldX.setText("0");

        jTextFieldY.setText("0");

        jButtonRGB.setText("RGB");
        jButtonRGB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRGBMouseClicked(evt);
            }
        });

        jPanelRGB.setBackground(new java.awt.Color(146, 146, 146));

        jLabelRed.setText("R: 0");

        jLabelGreen.setText("G: 0");

        jLabelBlue.setText("B: 0");

        javax.swing.GroupLayout jPanelRGBLayout = new javax.swing.GroupLayout(jPanelRGB);
        jPanelRGB.setLayout(jPanelRGBLayout);
        jPanelRGBLayout.setHorizontalGroup(
            jPanelRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRGBLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabelRed, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)
                    .addComponent(jLabelGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jLabelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
        jPanelRGBLayout.setVerticalGroup(
            jPanelRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRGBLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(jPanelRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRed)
                        .addComponent(jLabelGreen)
                        .addComponent(jLabelBlue))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelUkuran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelLebar.setText("Lebar: 0");

        jLabelTinggi.setText("Tinggi: 0");

        javax.swing.GroupLayout jPanelUkuranLayout = new javax.swing.GroupLayout(jPanelUkuran);
        jPanelUkuran.setLayout(jPanelUkuranLayout);
        jPanelUkuranLayout.setHorizontalGroup(
            jPanelUkuranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
            .addGroup(jPanelUkuranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUkuranLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabelTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jLabelLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        jPanelUkuranLayout.setVerticalGroup(
            jPanelUkuranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelUkuranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUkuranLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanelUkuranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTinggi)
                        .addComponent(jLabelLebar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButtonGrayscale.setText("Grayscale");
        jButtonGrayscale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGrayscaleMouseClicked(evt);
            }
        });

        jLabelPesanError.setForeground(new java.awt.Color(241, 64, 24));

        jButtonHistogram.setText("Histogram");
        jButtonHistogram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHistogramMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanelRGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanelUkuran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAmbilGambar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRGB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGrayscale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHistogram)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldY)))
                            .addComponent(jLabelPesanError))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAmbilGambar)
                    .addComponent(jButtonRGB)
                    .addComponent(jButtonGrayscale)
                    .addComponent(jButtonHistogram))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPesanError))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String sumber;
    Image GambarIkon;
    int ukuranX;
    int ukuranY;
    BufferedImage gambar;

    private void jButtonAmbilGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAmbilGambarMouseClicked
        // kode yang dikerjakan saat tombol 'ambil gambar' diklik
        JFileChooser buka = new JFileChooser();
        int ambil = buka.showOpenDialog(jScrollPane1);

        if (ambil == JFileChooser.APPROVE_OPTION) {
            sumber = buka.getSelectedFile().getPath();
            jLabelGambar.setIcon(new ImageIcon(sumber));
        }

        GambarIkon = new ImageIcon(sumber).getImage();
        ukuranX = GambarIkon.getWidth(null);
        ukuranY = GambarIkon.getHeight(null);

        jLabelLebar.setText("Lebar: " + ukuranX + " px");
        jLabelTinggi.setText("Tinggi: " + ukuranY + " px");

    }//GEN-LAST:event_jButtonAmbilGambarMouseClicked

    // method untuk meload gambar
    public static BufferedImage loadImage(String ref) {
        BufferedImage bimg = null;

        try {
            bimg = ImageIO.read(new File(ref));
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }

        return bimg;
    }

    // Method untuk menyesuaikan ukuran gambar dengan ukuran jLabel
    public static BufferedImage resize(BufferedImage img, int newW, int newH) {
        int w = img.getWidth();
        int h = img.getHeight();

        BufferedImage dimg = new BufferedImage(newW, newH, img.getType());
        Graphics2D grafik = dimg.createGraphics();
        grafik.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        grafik.drawImage(img, 0, 0, newW, newH, 0, 0, w, h, null);
        grafik.dispose();
        return dimg;
    }

    private void jButtonRGBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRGBMouseClicked
        // Kode yang dikerjakan saat tombol RGB diklik
        try { // TUGAS 1 - Membuat error handleing dengan TRY-CATCH
            BufferedImage loadImg = loadImage(sumber);
            int x = Integer.parseInt(jTextFieldX.getText());
            int y = Integer.parseInt(jTextFieldY.getText());

            int rgb = loadImg.getRGB(x, y);

            // ekstrak RGB
            int merah = (rgb >> 16) & 0xff;
            int hijau = (rgb >> 8) & 0xff;
            int biru = (rgb >> 0) & 0xff;

            jLabelRed.setText("R: " + Integer.toString(merah));
            jLabelGreen.setText("G: " + Integer.toString(hijau));
            jLabelBlue.setText("B: " + Integer.toString(biru));

        } catch (Exception e) {
            jLabelPesanError.setText("Ukuran X dan Y melampaui batas!");
        }
    }//GEN-LAST:event_jButtonRGBMouseClicked

    private void jButtonGrayscaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGrayscaleMouseClicked
        // kode yang dikerjakan saat tombol grayscale diklik
        BufferedImage prosesGambar;
        ukuranX = GambarIkon.getWidth(null);
        ukuranY = GambarIkon.getHeight(null);

        BufferedImage loadImg = loadImage(sumber);
        prosesGambar = new BufferedImage(ukuranX, ukuranY, BufferedImage.TYPE_INT_RGB);
        Graphics grafik = prosesGambar.getGraphics();

        grafik.drawImage(GambarIkon, 0, 0, null);

        for (int x = 0; x < ukuranX; x++) {
            for (int y = 0; y < ukuranY; y++) {

                int rgb = loadImg.getRGB(x, y);
                int alpha = (rgb << 24) & 0xff;
                int merahGrey = (rgb >> 16) & 0xff;
                int hijauGrey = (rgb >> 8) & 0xff;
                int biruGrey = (rgb >> 0) & 0xff;

                int rataRata = (merahGrey + hijauGrey + biruGrey) / 3;
                int grayscale = alpha | rataRata << 16 | rataRata << 8 | rataRata;
                prosesGambar.setRGB(x, y, grayscale);

            }
        }

        jLabelGambar.setIcon(new ImageIcon(prosesGambar));

    }//GEN-LAST:event_jButtonGrayscaleMouseClicked

    private void jButtonHistogramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistogramMouseClicked
        // Kode yang dikerjakan saat tombol hostogram diklik
        BufferedImage prosesGambar;
        ukuranX = GambarIkon.getWidth(null);
        ukuranY = GambarIkon.getHeight(null);

        BufferedImage loadImg = loadImage(sumber);
        prosesGambar = new BufferedImage(ukuranX, ukuranY, BufferedImage.TYPE_INT_RGB);
        Graphics grafik = prosesGambar.getGraphics();

        grafik.drawImage(GambarIkon, 0, 0, null);

        for (int x = 0; x < ukuranX; x++) {
            for (int y = 0; y < ukuranY; y++) {

                int rgb = loadImg.getRGB(x, y);
                int alpha = (rgb << 24) & 0xff;
                int merahGrey = (rgb >> 16) & 0xff;
                int hijauGrey = (rgb >> 8) & 0xff;
                int biruGrey = (rgb >> 0) & 0xff;

                int rataRata = (merahGrey + hijauGrey + biruGrey) / 3;
                int grayscale = alpha | rataRata << 16 | rataRata << 8 | rataRata;
                //prosesGambar.setRGB(x, y, grayscale);

            }
        }

        jLabelGambar.setIcon(new ImageIcon(prosesGambar));
        bikinHistogram(prosesGambar, "Grafik Citra");
    }//GEN-LAST:event_jButtonHistogramMouseClicked

    // Method untuk membuat histogram
    public void bikinHistogram(BufferedImage gmbr, String judul) {
        int lebar = gmbr.getWidth();
        int tinggi = gmbr.getHeight();
        int count[][] = new int[4][0x100];
        int merah = 0;
        int biru = 1;
        int hijau = 2;
        int total = lebar * tinggi;

        try {
            for (int x = 0; x < lebar; x++) {
                for (int y = 0; y < tinggi; y++) {

                    int rgb = gmbr.getRGB(x, y);
                    int merahGrey = (rgb >> 16) & 0xff;
                    int hijauGrey = (rgb >> 8) & 0xff;
                    int biruGrey = (rgb >> 0) & 0xff;
                    int grey = (merahGrey + hijauGrey + biruGrey) / 3;

                    count[merah][merahGrey]++;
                    count[biru][biruGrey]++;
                    count[hijau][hijauGrey]++;
                    count[3][grey]++;

                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        // membuat dataset dan mengisinya dengan perulangan
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int f = 0; f < 0x100; f++) {
            dataset.addValue(count[0][f], "Red", new Integer(f));
            dataset.addValue(count[2][f], "Blue", new Integer(f));
            dataset.addValue(count[1][f], "Green", new Integer(f));
            dataset.addValue(count[3][f], "Black", new Integer(f));
        }

        JFreeChart histo = ChartFactory.createBarChart("Histogram Citra", "Nilai", "Frekuensi", dataset,
                PlotOrientation.VERTICAL, true, true, false);

        ChartFrame frame = new ChartFrame("Histogram Citra", histo);
        histo.setBackgroundPaint(Color.white);
        final CategoryPlot plot = (CategoryPlot) histo.getPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeMinorGridlinePaint(Color.white);

        frame.setSize(500, 300);
        frame.setLocation(380, 200);
        frame.setTitle(judul);
        frame.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmbilGambar;
    private javax.swing.JButton jButtonGrayscale;
    private javax.swing.JButton jButtonHistogram;
    private javax.swing.JButton jButtonRGB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBlue;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JLabel jLabelGreen;
    private javax.swing.JLabel jLabelLebar;
    private javax.swing.JLabel jLabelPesanError;
    private javax.swing.JLabel jLabelRed;
    private javax.swing.JLabel jLabelTinggi;
    private javax.swing.JPanel jPanelRGB;
    private javax.swing.JPanel jPanelUkuran;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    // End of variables declaration//GEN-END:variables
}
